#!/bin/sh -e

mkdir -p build-aux

if test -x "`which glibtoolize 2> /dev/null || true`"; then
    glibtoolize -f -c --automake
else
    libtoolize -f -c --automake
fi

aclocal
autoheader -f
automake -f -c -a --gnits 2>&1 | sed -e "/install/d"
autoconf -f
